services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skopiaprojetos_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SkopiaDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy